language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
addons:
  firefox: "66.0"
  chrome: stable
cache:
  directories:
    - node_modules
    - /home/travis/.cache/Cypress
install:
  - npm install
  - cypress install
script:
  - npm run test