language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
addons:
  firefox: "66.0"
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install
# before_script:
#   - npm run lint
script:
  # - polymer test
  - xvfb-run polymer test
  # - xvfb-run npm run test:integration