language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
addons:
  firefox: "66.0"
  chrome: stable
cache:
  directories:
    - node_modules
services:
  - xvfb
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - xvfb-run npm run test:browsers
after_script:
  - codeclimate < coverage/**/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT